### PR TITLE
Remove USING BTREE

### PR DESCRIPTION
**Pull request by frrad**
This PR applies the patch left by PikMaster in a comment on https://github.com/dumblob/mysql2sqlite/issues/32

### CODE REVIEW

**Comment by dumblob** [comment]
Thanks for the code! Could you please also add a corresponding unit test to `unit_tests.sh` (it's still work in progress due to lack of time, but we're getting there :wink:)? I'd like to make it a [commit policy](https://github.com/dumblob/mysql2sqlite/issues/8 ).

**Comment by frrad** [comment]
Hey! All credit to @PikMaster for the original patch. 

I'm more than happy to add a test case which demonstrates this change. However I'm having a bit of trouble telling if the change causes any regressions in the existing tests.

How do you feel about the following test refactor (which I would be happy to contribute in a separate PR)

1. move the heredocs into separate files in a new test directory
1. write a smalls script to apply `mysql2sqlite` to them
1. check in their output

That way it's just a matter of running the script before submitting a PR. Any regression will cause a change to the output files.

**Comment by jagarsoft** [comment]
Hi @frrad 

I'm working on #8 
Would you so kind having a look at and align your test to it... if it is possible ;-)
Thanks in advance!

**Comment by dumblob** [comment]
@jagarsoft Sorry for not replying earlier (my time constraints are not getting smaller :cry:). I feel it's getting too big. Plain POSIX shell (with POSIX utilities) is an extremely high level language and I'm certain we shall use it to our advantage. The current `unit_tests.sh` just showcases how extremely easy it is to make unit tests. As a rule of thumb it would be very unwise to introduce any dependency or any more complicated structure than the `mysql2sqlite` script itself.

@frrad I'm happy to hear that. But what would be the advantage of the approach of splitting everything into separate files (assuming we'll never have thousands of heredocs and if it shall happen, it's super easy to split `unit_tests.sh` into separate files e.g. with groups/classes of unit tests)? Currently we also can (we shall as that's the very initial motivation) run `unit_tests.sh` as commit policy (provided it's polished and thus also without the `exit 1` line).

**Comment by frrad** [comment]
Updated the PR to include a test case in the current heredoc format. 

I also created https://github.com/dumblob/mysql2sqlite/pull/60 with an example of what I was suggesting. Feel free to take it or leave it. Seems like there is already a lot of thought going into how to do unit tests.

**Comment by frrad** [comment]
Hi @dumblob I'd love to merge this PR if possible. I've tried to conform to the current heredoc test style in my test case.

**Comment by frrad** [comment]
@dumblob any chance we could merge this?

**Comment by dumblob** [comment]
@frrad I'm sorry for being so inactive - I'm super busy these days, so thanks for being persistent with urging.

**Pull request merged**
