### PR TITLE
Issues with CHARACTER SET

### PR DESCRIPTION
**Pull request by murrant**
Make the space before the comma optional (unless you think it is safe to remove it)

### CODE REVIEW

**Comment by dumblob** [comment]
Could you please provide the .sql file where the current matching doesn't work? I'm asking because usually the dumps contain spaces at the end of line (pretty much like *COLLATE|collate* etc.).

**Comment by dumblob** [comment]
@murrant I'd like to resolve your issue with spaces, but the proposed solution seems hacky to me. Could you please provide the `.sql` file so that I can take a look?

**Comment by murrant** [comment]
The issue is the message field.

```
CREATE TABLE `eventlog` (
  `event_id` int(11) NOT NULL AUTO_INCREMENT,
  `host` int(11) NOT NULL DEFAULT '0',
  `datetime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `message` text CHARACTER SET latin1,
  `type` varchar(64) CHARACTER SET latin1 DEFAULT NULL,
  `reference` varchar(64) CHARACTER SET latin1 NOT NULL,
  PRIMARY KEY (`event_id`),
  KEY `host` (`host`),
  KEY `datetime` (`datetime`)
) ENGINE=InnoDB AUTO_INCREMENT=51470 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

**Comment by dumblob** [comment]
Ok, thanks for the snippet. The second patch looks safe so I merged it.

**Comment by murrant** [comment]
Yeah, the first patch was definitely wrong.  It removed **everything** after `CHARACTER SET`.
Thanks!

**Pull request merged**
